/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacksPackIdRouteImport } from './routes/packs.$packId'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as ApiPacksPackIdRouteImport } from './routes/api/packs.$packId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackIdRoute = PacksPackIdRouteImport.update({
  id: '/packs/$packId',
  path: '/packs/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksPackIdRoute = ApiPacksPackIdRouteImport.update({
  id: '/api/packs/$packId',
  path: '/api/packs/$packId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/api/packs/$packId': typeof ApiPacksPackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/api/packs/$packId': typeof ApiPacksPackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/api/packs/$packId': typeof ApiPacksPackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/telemetry' | '/packs/$packId' | '/api/packs/$packId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/telemetry' | '/packs/$packId' | '/api/packs/$packId'
  id:
    | '__root__'
    | '/'
    | '/api/telemetry'
    | '/packs/$packId'
    | '/api/packs/$packId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  PacksPackIdRoute: typeof PacksPackIdRoute
  ApiPacksPackIdRoute: typeof ApiPacksPackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packId': {
      id: '/packs/$packId'
      path: '/packs/$packId'
      fullPath: '/packs/$packId'
      preLoaderRoute: typeof PacksPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/$packId': {
      id: '/api/packs/$packId'
      path: '/api/packs/$packId'
      fullPath: '/api/packs/$packId'
      preLoaderRoute: typeof ApiPacksPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  PacksPackIdRoute: PacksPackIdRoute,
  ApiPacksPackIdRoute: ApiPacksPackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
